language: php
dist: trusty
sudo: false
cache:
  directories:
    - $HOME/.composer/cache
    - .phpunit
env:
  global:
    - MIN_PHP=7.1.3
    - SYMFONY_PHPUNIT_DIR="$HOME/symfony-bridge/.phpunit"
matrix:
  fast_finish: true
  include:
    - php: 7.1.3
    - php: 7.1
      env: deps=high
    - php: 7.2
      env: deps=low
before_install:
  - composer self-update
install:
  - composer install
  - ./vendor/bin/simple-phpunit install
script:
  - ./vendor/bin/simple-phpunit
  - ./vendor/bin/php-cs-fixer fix --diff --dry-run -v
  - composer validate --strict
notifications:
  email:
    on_success: never
    on_failure: always
