language: php
dist: trusty
sudo: false
cache:
  directories:
  - $HOME/.composer/cache
  - .phpunit
  - vendor/
env:
  global:
  - MIN_PHP=7.4
  - SYMFONY_PHPUNIT_DIR="$HOME/symfony-bridge/.phpunit"
matrix:
  fast_finish: true
  include:
  - php: 7.4
    env: deps=high
  - php: 7.4.2
    env: deps=low
before_install:
- curl -sS https://getcomposer.org/installer | php
install:
- composer install --optimize-autoloader
script:
- composer validate --strict
- php vendor/bin/simple-phpunit
- ./vendor/bin/php-cs-fixer fix -v --dry-run --stop-on-violation --using-cache=no
notifications:
  email:
    on_success: never
    on_failure: always
